### ISSUE TITLE
Conflicting requirements

### ISSUE THREAD

**Issue by mattiasa** [tonycpsu/mlbstreamer#27]
With the latest changes I get:

```
(mlbstreamer2) : lapetus mlbstreamer (master) \$ ; mlbplay
Traceback (most recent call last):
  File "/Users/mattiasa/.virtualenvs/mlbstreamer2/bin/mlbplay", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/mattiasa/.virtualenvs/mlbstreamer2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/Users/mattiasa/.virtualenvs/mlbstreamer2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/Users/mattiasa/.virtualenvs/mlbstreamer2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/mattiasa/.virtualenvs/mlbstreamer2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/mattiasa/.virtualenvs/mlbstreamer2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/mattiasa/.virtualenvs/mlbstreamer2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urwid-utils 0.1.1.dev0 (/Users/mattiasa/.virtualenvs/mlbstreamer2/lib/python2.7/site-packages/urwid_utils-0.1.1.dev0-py2.7.egg), Requirement.parse('urwid-utils==0.1.0.dev5'), set(['panwid']))
```

when installing from the source repo. Do we have to have an exact version requirement on urwid-utils or can we use semver to specify a minimum version=

**Comment by tonycpsu** [comment]
I noticed that this morning and will be pushing fixes.

**Comment by tonycpsu** [comment]
I think this one should be fixed now with a `pip install -U mlbstreamer`.  I've bumped the version requirements for panwid and urwid-utils released versions.

**Comment by mattiasa** [comment]
Yes, looks fixed!
