### ISSUE TITLE
requests.exceptions.SSLError when mlbplay --init-config

### ISSUE THREAD

**Issue by doehrm** [tonycpsu/mlbstreamer#30]
I'm trying to set up mlbplay on an Ubuntu 16.04.4:

```
MLB.tv username: XXXXXX@XXXX.XXX
Enter password: ********
2018-04-12 11:41:18 [   DEBUG] checking for existing log in
2018-04-12 11:41:19 [   DEBUG] attempting new log in
Traceback (most recent call last):
  File "/usr/local/bin/mlbplay", line 9, in <module>
    load_entry_point('mlbstreamer==0.0.8', 'console_scripts', 'mlbplay')()
  File "/usr/local/lib/python2.7/dist-packages/mlbstreamer/play.py", line 235, in main
    config.settings.init_config()
  File "/usr/local/lib/python2.7/dist-packages/mlbstreamer/config.py", line 112, in init_config
    s = MLBSession(self.username, self.password)
  File "/usr/local/lib/python2.7/dist-packages/mlbstreamer/session.py", line 96, in __init__
    self.login()
  File "/usr/local/lib/python2.7/dist-packages/mlbstreamer/session.py", line 165, in login
    headers={"Referer": (initial_url)}
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='securea.mlb.com', port=443): Max retries exceeded with url: /authenticate.do (Caused by SSLError(CertificateError("hostname 'securea.mlb.com' doesn't match either of '*.akamaized.net', '*.akamaihd-staging.net', '*.akamaized-staging.net', '*.akamaihd.net', 'a248.e.akamai.net'",),))
```

If I open that site (https://securea.mlb.com/) directly I also get NET::ERR_CERT_COMMON_NAME_INVALID in chrome.

Is there any option to overcome the certificate warning?

Thank you for all your work on this!

Markus

**Comment by tonycpsu** [comment]
I don't have a 16.04 machine to test with right now.  Can you try `pip install -U requests` and try again?

**Comment by doehrm** [comment]
```
$ pip install -U requests

Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests)
```

Thank you!

**Comment by tonycpsu** [comment]
Well, I just created a brand new Ubuntu 16.04 virtual machine, installed mpv and mlbstreamer, and am not running into these problems.  This suggests there might be something in your config that's different.  Have you set the `REQUESTS_CA_BUNDLE` environment variable, or done anything else to change your system's SSL certificate authorities?  Otherwise I'm pretty much stumped here, as it works for me on your operating system in a clean install.

**Comment by eithrial** [comment]
If you were using Lazyman, you can check if there are some modifications in /etc/hosts. They cause certification issues if you watch mlb.tv in legal way.

**Comment by doehrm** [comment]
Thank you for your feedback! I used a Smart DNS proxy, after that was switched off, it worked.
