### ISSUE TITLE
Errors in Ubuntu 18.04

### ISSUE THREAD

**Issue by kermitfan22** [tonycpsu/mlbstreamer#35]
I recently had to re-install my OS, and chose 18.04. After getting the OS installed, I wanted to re-install mlbstreamer as well, it was so easy and wonderful on Ubuntu 16.04.  This time I've run into error after error, and  now I'm stumped.
Python 2.7.15rc1

Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 7, in <module>
    from streamlink_cli.main import main
  File "/home/myth/.local/lib/python2.7/site-packages/streamlink_cli/main.py", line 21, in <module>
    from streamlink import __version__ as streamlink_version
  File "/home/myth/.local/lib/python2.7/site-packages/streamlink/__init__.py", line 86, in <module>
    from .api import streams
  File "/home/myth/.local/lib/python2.7/site-packages/streamlink/api.py", line 1, in <module>
    from .session import Streamlink
  File "/home/myth/.local/lib/python2.7/site-packages/streamlink/session.py", line 9, in <module>
    from streamlink.logger import StreamlinkLogger, Logger
  File "/home/myth/.local/lib/python2.7/site-packages/streamlink/logger.py", line 7, in <module>
    from streamlink.compat import is_py2
  File "/home/myth/.local/lib/python2.7/site-packages/streamlink/compat.py", line 48, in <module>
    from backports.shutil_which import which
ImportError: No module named shutil_which

This is actually the second of such errors I've run into.  Please let me know what else I need to install to make this work!

**Comment by tonycpsu** [comment]
The exception is coming from the streamlink installation, which is a run-time dependency of mlbstreamer.  I suspect you'll get the same results if you "pip install streamlink", and, if so, I think you'll get better results asking over [here](https://github.com/streamlink/streamlink).
