### ISSUE TITLE
mlbstreamer won't start & mlbplay doesn't load player

### ISSUE THREAD

**Issue by icediamond** [tonycpsu/mlbstreamer#40]
When I try to run mlbstreamer, I get this error:

Traceback (most recent call last):
  File "C:\Users\Bob\Downloads\WinPython-37\python-3.7.2.amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Bob\Downloads\WinPython-37\python-3.7.2.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Bob\Downloads\WinPython-37\python-3.7.2.amd64\Scripts\mlbstreamer.exe\__main__.py", line 9, in <module>
  File "C:\Users\Bob\Downloads\WinPython-37\python-3.7.2.amd64\lib\site-packages\mlbstreamer\__main__.py", line 525, in main
    screen = urwid.raw_display.Screen()
  File "C:\Users\Bob\Downloads\WinPython-37\python-3.7.2.amd64\lib\site-packages\urwid\raw_display.py", line 92, in __init__
    fcntl.fcntl(self._resize_pipe_rd, fcntl.F_SETFL, os.O_NONBLOCK)
NameError: name 'fcntl' is not defined

Also, when trying to use mlbplay, nothing happens. I put in all of the parameters and...nothing happens...at all.

**Comment by icediamond** [comment]
Nevermind I figured out a better way

**Comment by suedunham** [comment]
Actually, I'm getting the same error. Just installed mlbstreamer on Windows, and I've at least gotten as far with that process to get this error. I wound up needing a binary of [blist from here](https://www.lfd.uci.edu/~gohlke/pythonlibs/), which seemed to complete the installation, but I haven't gotten mlbplay or mlbstreamer to load anything.

icediamond, what did you figure out?

**Comment by icediamond** [comment]
I figured out updated filters on my uBlock seem to have stopped the commercials!

(I also did the same workaround for blist but ended up with the urwid error)

**Comment by suedunham** [comment]
Reading around more, I see with --verbose engaged in mlbplay that this is another manifestation of [errors: not-entitled](https://github.com/tonycpsu/mlbstreamer/issues/43) issue.
