### ISSUE TITLE
Failing with Exception(authz_content)

### ISSUE THREAD

**Issue by sdelafond** [tonycpsu/mlbstreamer#41]
0.0.11.dev0 worked fine yesterday to download a stream, an effectively fixed the "not-entitled" problem. However, today I'm getting:

```
# mlbplay -v -s 2019-04-01_sf.ogg 2019-04-01.sf
2019-04-02 08:57:13 [         session:306 ] [   DEBUG] getting schedule: 1, 2019-04-01 00:00:00, 2019-04-01 00:00:00, None, 137, None
2019-04-02 08:57:14 [            play:106 ] [    INFO] playing game 565803 at 720p_alt
2019-04-02 08:57:14 [         session:344 ] [   DEBUG] geting media for game 565803 (None, None, None)
2019-04-02 08:57:14 [         session:306 ] [   DEBUG] getting schedule: 1, None, None, None, None, 565803
2019-04-02 08:57:14 [         session:358 ] [   DEBUG] found preferred stream
2019-04-02 08:57:14 [         session:557 ] [   DEBUG] refreshing access token
2019-04-02 08:57:14 [            play:32  ] [   ERROR] Uncaught exception
Traceback (most recent call last):
  File "/bin/mlbplay", line 11, in <module>
    load_entry_point('mlbstreamer==0.0.11.dev0', 'console_scripts', 'mlbplay')()
  File "/usr/lib/python3/dist-packages/mlbstreamer/play.py", line 380, in main
    verbose = options.verbose
  File "/usr/lib/python3/dist-packages/mlbstreamer/play.py", line 153, in play_stream
    stream = state.session.get_stream(media)
  File "/usr/lib/python3/dist-packages/mlbstreamer/session.py", line 834, in get_stream
    "Authorization": self.access_token,
  File "/usr/lib/python3/dist-packages/mlbstreamer/session.py", line 548, in access_token
    self.refresh_access_token()
  File "/usr/lib/python3/dist-packages/mlbstreamer/session.py", line 587, in refresh_access_token
    raise Exception(authz_content)
Exception: <!DOCTYPE html>
<html>
<head>
    <title>Signing in...</title>
    <script type="text/javascript">
[...]
```

**Comment by sdelafond** [comment]
streamglob as of commitid 5bb1c67 doesn't have this problem.

**Comment by tonycpsu** [comment]
Hm, can't reproduce this one here.  Tried with my saved session, tried removing `~/.config/mlbstreamer/mlb.*` to get a new session...  Works fine for me.  The login/entitlement code should be pretty much the same between the two.

**Comment by sdelafond** [comment]
Interesting; I was able to reproduce it just now, however removing everything except config.yaml in ~/.config/mlbstreamer did the job:

```
rm ~/.config/mlbstreamer/{mlb,session,cache.sqlite,cookies}
```

I guess you can close this issue. Thanks a lot for taking the time to look into it. I'll try to get 0.0.11.dev0 in Debian's buster before it's released.

**Comment by tonycpsu** [comment]
> Interesting; I was able to reproduce it just now, however removing everything except config.yaml in ~/.config/mlbstreamer did the job:

OK.  I do think there could be some issues related to sessions timing out / not refreshing properly, but until I see them myself it's hard to get under the hood and debug them.  

> I'll try to get 0.0.11.dev0 in Debian's buster before it's released.

Great!  Hopefully by the next Debian release `streamglob` is in a state more worthy of inclusion.
