### ISSUE TITLE
--init-config not working on macos pyenv python 3.7.3

### ISSUE THREAD

**Issue by webern** [tonycpsu/mlbstreamer#48]
I installed Python 3.7.3 on macOS using pyenv. Then ran `pip install mlbstreamer` and attempted to `--init-config`

Here is the result. Not a Python guy. What should I try next? Thanks.

```
mymac:~ macuser$ mlbplay --init-config
MLB.tv username: some-email-address@gmail.com
Enter password: ****************
Traceback (most recent call last):
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/urllib3/connection.py", line 316, in connect
    conn = self._new_conn()
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1059c6320>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='web-secure.mlb.com', port=443): Max retries exceeded with url: /enterworkflow.do?flowId=registration.newsletter&c_id=mlb (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1059c6320>: Failed to establish a new connection: [Errno 60] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macuser/.pyenv/versions/3.7.3/bin/mlbplay", line 11, in <module>
    load_entry_point('mlbstreamer==0.0.10', 'console_scripts', 'mlbplay')()
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mlbstreamer/play.py", line 314, in main
    config.settings.init_config()
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mlbstreamer/config.py", line 112, in init_config
    s = MLBSession(self.username, self.password)
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mlbstreamer/session.py", line 121, in __init__
    self.login()
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mlbstreamer/session.py", line 259, in login
    if self.logged_in:
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mlbstreamer/session.py", line 284, in logged_in
    content = self.get(logged_in_url).text
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mlbstreamer/session.py", line 154, in request
    response = method(url, *args, **kwargs)
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/macuser/.pyenv/versions/3.7.3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='web-secure.mlb.com', port=443): Max retries exceeded with url: /enterworkflow.do?flowId=registration.newsletter&c_id=mlb (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1059c6320>: Failed to establish a new connection: [Errno 60] Operation timed out'))
mymac:~ macuser$
```

**Comment by thoskam** [comment]
I am getting the same error on Rasbian with Python 3.73

**Comment by tonycpsu** [comment]
Sorry folks, `mlbstreamer` isn't supported anymore.  Try [streamglob](https://github.com/tonycpsu/streamglob).
