### ISSUE TITLE
A connecion attempt failed

### ISSUE THREAD

**Issue by mlb-fan** [tonycpsu/mlbstreamer#49]
I need to get a few games downloaded before my MLBtv account expires, I had previously used mlbv but came here after encountering [an issue](https://github.com/kmac/mlbv/issues/41) that isn't getting a response with time short to get things working.

I got everything for mlbstreamer to install and when I run mlbplay --init-config it starts to work, but after I provide my login and password it sits for a few moments then says this:

> Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\urllib3\connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "c:\program files\python38\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "c:\program files\python38\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed
 because connected host has failed to respond

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
File "c:\program files\python38\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "c:\program files\python38\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "c:\program files\python38\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "c:\program files\python38\lib\site-packages\urllib3\connection.py", line 334, in connect
    conn = self._new_conn()
  File "c:\program files\python38\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004FDAF70>: Failed to establish a new connection: [WinError 10060]
 A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has fa
iled to respond

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
File "c:\program files\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\program files\python38\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "c:\program files\python38\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='web-secure.mlb.com', port=443): Max retries exceeded with url: /enterworkflow.do?flowId=registration.newslet
ter&c_id=mlb (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004FDAF70>: Failed to establish a new connection: [WinError 1
0060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host h
as failed to respond'))

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
File "C:\Program Files\Python38\Scripts\mlbplay-script.py", line 11, in <module>
    load_entry_point('mlbstreamer==0.0.10', 'console_scripts', 'mlbplay')()
  File "c:\program files\python38\lib\site-packages\mlbstreamer\play.py", line 314, in main
    config.settings.init_config()
  File "c:\program files\python38\lib\site-packages\mlbstreamer\config.py", line 112, in init_config
    s = MLBSession(self.username, self.password)
  File "c:\program files\python38\lib\site-packages\mlbstreamer\session.py", line 121, in __init__
    self.login()
  File "c:\program files\python38\lib\site-packages\mlbstreamer\session.py", line 259, in login
    if self.logged_in:
  File "c:\program files\python38\lib\site-packages\mlbstreamer\session.py", line 284, in logged_in
    content = self.get(logged_in_url).text
  File "c:\program files\python38\lib\site-packages\mlbstreamer\session.py", line 154, in request
    response = method(url, *args, **kwargs)
  File "c:\program files\python38\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "c:\program files\python38\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\program files\python38\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\program files\python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='web-secure.mlb.com', port=443): Max retries exceeded with url: /enterworkflow.do?flowId=registration.news
letter&c_id=mlb (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004FDAF70>: Failed to establish a new connection: [WinErro
r 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected hos
t has failed to respond'))

**Comment by tonycpsu** [comment]
Try [streamglob](https://github.com/tonycpsu/streamglob), which is the successor to `mlbstreamer`, has been kept up-to-date with changes to MLB's streaming infrastructure as of the 2019 regular season, and, at least for me, isn't exhibiting this problem.

**Comment by mlb-fan** [comment]
I tried that next, but the configuration isn't working. It doesn't seem to be usable on Windows.
Also there isn't documentation for it, so I don't know how to save games to disk even if it was running.

**Comment by mlb-fan** [comment]
I tried streamglob next, but I'm on Windows so usage failed when I got to [this point](https://github.com/tonycpsu/streamglob/issues/22)

EDIT: Now working on Windows! Thanks!
