### ISSUE TITLE
ubuntu 14.04

### ISSUE THREAD

**Issue by sam43434** [tonycpsu/mlbstreamer#7]
Hi, on my ubuntu 14.04 im getting, when trying to run mlbplay --init-config

Traceback (most recent call last):
  File "/usr/local/bin/mlbplay", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3195, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3179, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3208, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 681, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 999, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 893, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2728, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: urllib3 1.7.1 has no such extra feature 'secure'

**Comment by tonycpsu** [comment]
I don't have an Ubuntu box that old to try myself, but I'll see what I can do here.

Can you try `pip install -U "urllib3[secure]"` and try again?
